[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "self.ability.bonus = (self.ability.bonus or 0) + (center.config.bonus or 0)"
position = "after"
payload = "Talisman.effects.init_ability(self.ability, center.config)"
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "local p_dollars = card:get_p_dollars()"
position = "before"
payload = "Talisman.effects.evaluate_scoring_card(card, ret)"
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "elseif eval_type == 'dollars' then"
position = "before"
payload = '''
elseif Talisman.effects.list[eval_type] then
	local h = Talisman.effects.list[eval_type]
	sound = h.sound
	text = h.stringify(amt)
	colour = G.C[h.colorKey or 'WHITE']
	config.type = 'fade'
	config.scale = 0.7
	amt = h.hyper and amt[2] or amt
'''
match_indent = true

# sfx
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "sound = extra.edition and 'foil2' or extra.mult_mod and 'multhit1' or extra.Xmult_mod and 'multhit2' or 'generic1'"
position = "after"
payload = "sound = Talisman.effects.get_mod_sound(extra) or sound"
match_indent = true
