[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "self.ability.bonus = (self.ability.bonus or 0) + (center.config.bonus or 0)"
position = "after"
payload = "Talisman.effects.init_ability(self.ability, center.config)"
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "local p_dollars = card:get_p_dollars()"
position = "before"
payload = "Talisman.effects.evaluate_scoring_card(card, ret)"
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "local text = ''"
position = "before"
payload = '''
if eval_type ~= "extra" and Talisman.effects.list[eval_type] then
	extra = Talisman.effects.transform_loc(eval_type, amt, card, extra)
	eval_type = "extra"
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
config.scale = 0.7
end
'''
position = "after"
payload = '''
colour = extra.colour or colour
'''
match_indent = true
