[manifest]
version = "1.0.0"
priority = 0

# NOTE: all the patches below WILL FAIL if SMODS is present

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "if effects.jokers.Xmult_mod then mult = mod_mult(mult*effects.jokers.Xmult_mod);extras.mult = true  end"
position = "after"
payload = '''
for k,v in pairs(effects.jokers) do
	local fx = Talisman.effects.list[k]
	if fx then
		fx:setScore(v, effects.jokers)
		fx:effectExtra(v, extras)
	end
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "if effect.Xmult_mod then mult = mod_mult(mult*effect.Xmult_mod);extras.mult = true  end"
position = "after"
payload = '''
for k,v in pairs(effect) do
	local fx = Talisman.effects.list[k]
	if fx then
		fx:setScore(v, effect)
		fx:effectExtra(v, extras)
	end
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "if effects[ii].message then"
position = "before"
payload = '''
for k,v in pairs(effects[ii]) do
	local fx = Talisman.effects.list[k]
	if fx then
		mod_percent = true
		fx:setScore(v, effects[ii])
		fx:effectScore(v)
		card_eval_status_text(G.hand.cards[i], k, v, percent)
	end
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "--calculate the card edition effects"
position = "before"
payload = '''
for k,v in pairs(effects[ii]) do
	local fx = Talisman.effects.list[k]
	if fx then
		mod_percent = true
		fx:setScore(v, effects[ii])
		fx:effectScore(v)
		card_eval_status_text(scoring_hand[i], k, v, percent)
		if effects[ii].card then juice_card(effects[ii].card) end
	end
end
'''
match_indent = true

# my fix for this one is really scuffed
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = 'if edition_effects.jokers.x_mult_mod then'
position = 'before'
match_indent = true
payload = '''
if G.jokers.cards and G.jokers.cards[i] and G.jokers.cards[i].edition then
	local trg = G.jokers.cards[i]
	local edi = trg.edition

	for k,v in pairs(edi) do
		local fx = Talisman.effects.list[k]
		if fx then
			mod_percent = true
			fx:setScore(v, edi)
			fx:effectScore(v)
			card_eval_status_text(scoring_hand[i], k, v, percent)
			if effects[ii].card then juice_card(effects[ii].card) end

			card_eval_status_text(
				trg, 'extra', nil, percent, nil,
				{
					message = fx.stringify(v),
					edition = true,
					[k] = true
				}
			)
		end
	end
end
edition_effects.jokers.x_mult_mod = nil
'''
